server:
  port: 84

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/

#设置feign客户端超时时间(OpenFeign默认支持ribbon)(单位：毫秒)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000


#开启日志的OpenFeign客户端
logging:
  level:
    # OpenFeign日志以什么级别监控哪个接口
    com.wxw.springcloud.service.PaymentOpenFeignService: debug
